# Generated by Django 2.2.6 on 2019-10-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0002_auto_20191016_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_phonenumber',
            field=models.CharField(default='', max_length=20, verbose_name='nomer'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='Concert_name',
            field=models.CharField(default='', max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='Concert_place',
            field=models.CharField(default='', max_length=20, verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='Concert_time',
            field=models.CharField(default='', max_length=20, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_age',
            field=models.IntegerField(default='', verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_reputation',
            field=models.CharField(default='', max_length=20, verbose_name='reputation'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_sex',
            field=models.CharField(default='', max_length=20, verbose_name='sex'),
        ),
    ]
